
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


import_from_git(
   url: "https://oauth2:eBkSWpg1x8ozCSQdKyk9@git-oab.si.fr.intraorange/practice-apple-mds-o/fastlane-core.git",
   branch: "0.2.2",
   path: "Fastfile"
)


lane :build_project_test do
    check_mandatory_env_var
    init_version_number
    init_slack
    init_cocoapods
    init_automatic_code_signing
    init_gym(version: get_version_number)
    disable_automatic_signing
    gym(
      export_options: {
        compileBitcode: ENV["GYM_INCLUDE_BITCODE"],
        uploadBitcode: ENV["GYM_INCLUDE_BITCODE"],
        provisioningProfiles: {
          ENV["FL_BUNDLE_IDENTIFIER"] => ENV["PROVISIONING_IDENTIFIER"]
        }
      },
      xcargs: { :PROVISIONING_PROFILE => ENV["PROVISIONING_IDENTIFIER"]}
    )
  end
