# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

import_from_git(
   url: "https://oauth2:eBkSWpg1x8ozCSQdKyk9@git-oab.si.fr.intraorange/practice-apple-mds-o/fastlane-core.git",
   branch: "0.2.2",
   path: "Fastfile"
)

#xcversion(version: "10.1")

default_platform(:ios)

platform :ios do

end
