name: flutter_chat_example
description: A Chat Flutter
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  logging: ^0.11.3+2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_chat:
    path: ../

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
