name: flutter_chat_example
description: A Chat Flutter
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter_bloc: ^0.4.8
  firebase_messaging: ^1.0.2
  firebase_database: ^1.0.5
  logging: ^0.11.3+2
  image_picker: ^0.4.10
  photo_manager: ^0.1.8
  firebase_storage: ^1.0.2
  cached_network_image: ^0.4.1
  location: ^1.4.1
  google_maps_flutter: ^0.0.3+3
  firebase_auth: ^ 0.5.20
  giphy_client: ^0.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_chat:
    path: ../
  dio: ^1.0.1
  cupertino_icons: ^0.1.2

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
