name: flutter_chat_example
description: A Chat Flutter
version: 0.0.1+3
author:
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  logging: ^0.11.3+2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_chat:
    path: ../
  equatable: ^0.2.3
  google_sign_in: ^4.0.1+1

dev_dependencies:
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: "flutter_chat_example_app_icon"
  ios: "flutter_chat_example_app_icon"
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
