name: flutter_chat
description: A flutter chat.
version: 0.1.3

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase dependencies
  firebase_messaging: ^6.0.16
  firebase_database: ^3.1.6
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6

  # Other dependencies
  flutter_bloc: ^6.0.1
  equatable: ^1.2.3
  image_picker: ^0.6.7+4
  cached_network_image: ^2.0.0
  photo_view: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0

flutter:
  uses-material-design: true
