line_length:
  warning: 200
  error: 2000
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

file_length:
  warning: 500
  error: 1200
############################################
## TEMPLATE -> Replace XXXX
############################################
included:
- XXXX

  # binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly


trailing_whitespace:
  ignores_empty_lines: true

disabled_rules:
- function_body_length
- type_body_length
- file_length
- cyclomatic_complexity
- nesting
- identifier_name # temporary
