plugin 'cocoapods-art', :sources => [
'cocoapods-corporate',
'cocoapods-public'
]
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

# Do not display warning for Pods
inhibit_all_warnings!

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

$swift3pod = Array[]
$swift4pod = Array['R.swift.Library']

def app_pods
    pod 'SwiftLint'
    pod 'R.swift'
end

# REPLACE TARGET NAME XXXX
target 'Runner' do
    app_pods

    target 'XXXXTests' do
      inherit! :search_paths
      # Pods for testing
    end
end

post_install do |installer|
    puts "Post-Install: Patch SWIFT_VERSION"

    installer.pods_project.targets.each do |target|

        if $swift3pod.include?(target.name)
            print "Setting #{target.name}'s SWIFT_VERSION to 3.3\n"
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.3'
            end
        else
            if $swift4pod.include?(target.name)
                print "Setting #{target.name}'s SWIFT_VERSION to 4.0\n"
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '4.0'
                end
            else
                print "Setting #{target}'s SWIFT_VERSION to Undefined (Xcode will automatically resolve)\n"
                target.build_configurations.each do |config|
                    config.build_settings.delete('SWIFT_VERSION')
                end
            end
        end
    end


    puts "Post-Install: Patch ENABLE_BITCODE"

    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
